# All quiz questions for the coding course.
# phase 1-6 = phase quiz (10 questions each)
# phase 0 = synthesis questions used in the final 100-question test alongside all phase questions
#
# This file is the SINGLE SOURCE OF TRUTH for quiz content. Editing a question here
# propagates to the live quiz on the next restart — BUT ONLY IF you bump QUESTIONS_VERSION
# below. init_db() re-seeds quiz.db whenever the stored version differs from this one.
#
# IMPORTANT — question order is load-bearing. Each question's stable id is its 1-based
# position in this list, and quiz_answers rows reference those ids. Editing a question's
# text in place is safe. Do NOT reorder or delete existing questions (it would repoint
# historical answers to the wrong questions) — only append new ones at the end of a phase.
#
# The literal token {{LEARNER}} in any question is replaced with the current learner's
# name at render time (see personalize() in __init__.py). Numbers (ages, list values)
# are scenario data and are intentionally NOT personalized.
QUESTIONS_VERSION = 2

QUESTIONS = [

    # ===== PHASE 1: Tools, terminal, first code =====

    {
        "phase": 1,
        "text": "You type `python hello.py` and get: `can't open file 'hello.py': No such file or directory`. What is the most likely cause?",
        "a": "Python is not installed correctly on your computer.",
        "b": "Your terminal is in a different folder than where the file is saved.",
        "c": "The file does not exist anywhere on your computer.",
        "d": "The filename has a typo in your script.",
        "correct": "b",
        "explanation": "Python looks for files relative to the folder your terminal is currently in. If your terminal is in `Code Projects` but the file is inside `Code Projects/family-site`, Python cannot find it. The fix is to `cd` into the correct folder first.",
        "topic": "terminal",
        "difficulty": 1
    },
    {
        "phase": 1,
        "text": "You run `git add lessons/practice/hello.py` and nothing prints. What happened?",
        "a": "An error occurred but git is hiding it from you.",
        "b": "The file was successfully staged for the next commit.",
        "c": "The file was committed to the repository.",
        "d": "The file was uploaded to GitHub.",
        "correct": "b",
        "explanation": "Git is quiet when things work. `git add` stages the file — it marks it to be included in the next `git commit`. Nothing else has happened yet. No output means success.",
        "topic": "git",
        "difficulty": 1
    },
    {
        "phase": 1,
        "text": "After `git commit -m 'my changes'` you close your laptop. A teammate cannot see your changes on GitHub. Why?",
        "a": "Git commits are private by default and require approval.",
        "b": "You need to run `git add` again after committing.",
        "c": "You have not run `git push` yet.",
        "d": "The commit message was too short.",
        "correct": "c",
        "explanation": "`git commit` saves a snapshot locally on your machine only. `git push` is what sends it to GitHub where others can see it. Commit = local save. Push = share with the world.",
        "topic": "git",
        "difficulty": 1
    },
    {
        "phase": 1,
        "text": "Your Python script has this line: `print(\"Hello world)`. What error will you get?",
        "a": "NameError: name 'Hello' is not defined",
        "b": "SyntaxError: unterminated string literal",
        "c": "TypeError: expected str not tuple",
        "d": "IndentationError: unexpected indent",
        "correct": "b",
        "explanation": "You opened the string with a `\"` but never closed it. Python does not know where the string ends, so it reports an unterminated string literal. Every opening quote needs a matching closing quote.",
        "topic": "python",
        "difficulty": 1
    },
    {
        "phase": 1,
        "text": "The family site has a route `@dad_bp.route(\"/\")` inside the dad blueprint, which is registered with `url_prefix=\"/dad\"`. What URL does it respond to?",
        "a": "/",
        "b": "/dad_bp/",
        "c": "/dad/",
        "d": "/dad_bp/dad/",
        "correct": "c",
        "explanation": "The URL prefix and route path combine. `/dad` prefix + `/` route = `/dad/`. Every route inside a blueprint automatically gets the prefix prepended.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 1,
        "text": "You are on branch `about-me`. You commit your changes and push to GitHub. You visit your live Railway URL. Is your page there?",
        "a": "Yes — all pushes to GitHub update the live site.",
        "b": "No — your push only updated the `about-me` branch on GitHub, not `main`.",
        "c": "Yes, but only if you used `git push --force`.",
        "d": "No — you need to restart Gunicorn manually on Railway first.",
        "correct": "b",
        "explanation": "Railway deploys from `main` (or whichever branch you connected). Your feature branch is separate until Dad reviews and merges your PR. Merging to `main` triggers a new Railway deploy. This is the whole point of using branches.",
        "topic": "git",
        "difficulty": 2
    },
    {
        "phase": 1,
        "text": "What does `render_template(\"aboutme/index.html\")` actually do when a user visits your route?",
        "a": "It downloads the template file from the server to the user's computer.",
        "b": "It reads the HTML file, fills in any template variables, and sends the result to the user's browser.",
        "c": "It saves the HTML file to the user's computer.",
        "d": "It runs the HTML file as Python code.",
        "correct": "b",
        "explanation": "Flask finds the template file, processes any Jinja2 syntax like `{{ variable }}`, and returns the finished HTML to the browser. The user receives HTML — they never see the template syntax.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 1,
        "text": "You add a new blueprint called `aboutme_bp` but forget to call `app.register_blueprint()` in `app.py`. What happens when someone visits `/aboutme`?",
        "a": "Flask crashes on startup with an ImportError.",
        "b": "The page loads but without any CSS styling.",
        "c": "Flask returns a 404 Not Found error.",
        "d": "Flask redirects to the home page.",
        "correct": "c",
        "explanation": "Without registering the blueprint, Flask has no idea the routes inside it exist. Any URL that would have hit those routes simply returns 404. The blueprint's code is imported but its routes are invisible to Flask.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 1,
        "text": "You accidentally delete your `.env` file. What happens the next time you run `python app.py`?",
        "a": "The app runs but with reduced functionality.",
        "b": "The app crashes with a RuntimeError because SECRET_KEY is missing.",
        "c": "Flask creates a new .env file automatically.",
        "d": "The app runs fine — .env is only needed in production.",
        "correct": "b",
        "explanation": "The starter app checks for SECRET_KEY at startup and raises RuntimeError if it is missing. The app will not start at all. Copy `.env.example` to `.env` and set a real SECRET_KEY.",
        "topic": "security",
        "difficulty": 2
    },
    {
        "phase": 1,
        "text": "You are on Cursor's free (Hobby) tier and want to add a multi-file About Me feature. What is the best way to protect your monthly AI allowance?",
        "a": "Open ten separate Composer chats — one per file — so each task stays small.",
        "b": "Use Tab completion for every line and never open Composer.",
        "c": "Batch the work into one scoped Composer prompt for the whole feature, then explain every line before committing.",
        "d": "Ask Chat to write the entire app from scratch in one message.",
        "correct": "c",
        "explanation": "Composer/Agent usage is the most expensive part of the free tier. Batching related changes into one scoped prompt uses fewer requests than many micro-prompts. Tab is for small fixes; no-AI typing is for drills. Either way, the explain rule still applies before commit.",
        "topic": "cursor",
        "difficulty": 2
    },

    # ===== PHASE 2: Python and git fluency =====

    {
        "phase": 2,
        "text": "What does this print?\n```\nnames = [\"{{LEARNER}}\", \"Dad\", \"Mom\"]\nfor name in names:\n    print(name)\n```",
        "a": "[\"{{LEARNER}}\", \"Dad\", \"Mom\"] on one line",
        "b": "{{LEARNER}} Dad Mom on one line separated by spaces",
        "c": "{{LEARNER}}, then Dad, then Mom each on their own line",
        "d": "Nothing — you need `print(names)` not `print(name)`",
        "correct": "c",
        "explanation": "The loop runs once per item. Each iteration, `name` holds one person's name and `print(name)` prints it on its own line. Three iterations = three lines of output.",
        "topic": "python",
        "difficulty": 1
    },
    {
        "phase": 2,
        "text": "You have `family = {\"{{LEARNER}}\": 13, \"Dad\": 45}`. How do you get {{LEARNER}}'s age?",
        "a": "family[0]",
        "b": "family[\"{{LEARNER}}\"]",
        "c": "family.{{LEARNER}}",
        "d": "family.get(0)",
        "correct": "b",
        "explanation": "Dictionaries are accessed by key, not by position. `family[\"{{LEARNER}}\"]` returns the value `13` associated with that key. `family[0]` would fail — dictionaries do not have integer indexes.",
        "topic": "python",
        "difficulty": 1
    },
    {
        "phase": 2,
        "text": "What is the difference between `=` and `==` in Python?",
        "a": "They are interchangeable — use whichever you prefer.",
        "b": "`=` assigns a value to a variable. `==` checks if two things are equal.",
        "c": "`=` checks equality. `==` assigns a value.",
        "d": "`==` only works on numbers. `=` works on anything.",
        "correct": "b",
        "explanation": "`name = \"{{LEARNER}}\"` stores the value. `name == \"{{LEARNER}}\"` is a question: is name equal to {{LEARNER}}? It returns True or False. Mixing these up is one of the most common beginner bugs.",
        "topic": "python",
        "difficulty": 1
    },
    {
        "phase": 2,
        "text": "You define a function but forget to write `return`. What does the function give back when called?",
        "a": "0",
        "b": "An empty string \"\"",
        "c": "None",
        "d": "The last variable that was used inside the function",
        "correct": "c",
        "explanation": "In Python, a function with no `return` statement automatically returns `None`. This is one of the most common sources of bugs — you call a function expecting a value and get `None` instead.",
        "topic": "python",
        "difficulty": 2
    },
    {
        "phase": 2,
        "text": "This code has a bug. What is it?\n```\ndef greet(name):\n    message = \"Hello \" + name\n\nprint(greet(\"{{LEARNER}}\"))\n```",
        "a": "You cannot concatenate strings with `+` in Python.",
        "b": "The function never returns `message`, so it returns None and `None` gets printed.",
        "c": "`print` cannot call a function inside it.",
        "d": "`\"Hello \"` needs a comma, not a `+`.",
        "correct": "b",
        "explanation": "The function builds `message` but never does `return message`. So it returns `None`. `print(greet(\"{{LEARNER}}\"))` prints `None`. This is the missing `return` bug in action.",
        "topic": "python",
        "difficulty": 2
    },
    {
        "phase": 2,
        "text": "What does a merge conflict mean?",
        "a": "Git could not find the branch you tried to merge.",
        "b": "Two branches both changed the same part of the same file and Git cannot decide which version to keep.",
        "c": "The merge failed because of a Python syntax error in your code.",
        "d": "GitHub rejected your push because of a policy violation.",
        "correct": "b",
        "explanation": "Git can merge changes automatically when they are in different places. When two branches both edited the same lines, Git stops and asks you to decide which version is correct. You edit the file to resolve it, then commit.",
        "topic": "git",
        "difficulty": 2
    },
    {
        "phase": 2,
        "text": "You have a list `scores = [85, 92, 78]`. What does `scores[1]` return?",
        "a": "85",
        "b": "92",
        "c": "78",
        "d": "2",
        "correct": "b",
        "explanation": "List indexes start at 0, not 1. `scores[0]` is 85, `scores[1]` is 92, `scores[2]` is 78. This catches almost everyone off guard the first time.",
        "topic": "python",
        "difficulty": 1
    },
    {
        "phase": 2,
        "text": "What does this code print?\n```\nages = {\"{{LEARNER}}\": 13, \"Mom\": 42, \"Dad\": 45}\nfor person, age in ages.items():\n    if age < 18:\n        print(person)\n```",
        "a": "Everyone's name and age",
        "b": "Only {{LEARNER}}",
        "c": "13 (just the number)",
        "d": "It crashes because you cannot loop over a dict",
        "correct": "b",
        "explanation": "`.items()` gives you key-value pairs. The `if age < 18` filter means only {{LEARNER}} (age 13) passes. Only `\"{{LEARNER}}\"` gets printed. Mom (42) and Dad (45) are filtered out.",
        "topic": "python",
        "difficulty": 2
    },
    {
        "phase": 2,
        "text": "You are on branch `feature-x` and run `git merge main`. What does this do?",
        "a": "Sends your branch to GitHub.",
        "b": "Deletes the main branch.",
        "c": "Brings the latest changes from `main` into your `feature-x` branch.",
        "d": "Switches you to the `main` branch.",
        "correct": "c",
        "explanation": "`git merge main` takes the commit history of `main` and combines it into wherever you currently are (`feature-x`). Your branch gets `main`'s changes. You stay on `feature-x`.",
        "topic": "git",
        "difficulty": 2
    },
    {
        "phase": 2,
        "text": "A classmate hands you a Python file. You see `import json` at the top and `with open(\"data.json\")` in the middle. What can you already infer before reading any logic?",
        "a": "Nothing useful — you need to run it first.",
        "b": "The file probably reads or writes data from a JSON file called data.json.",
        "c": "The file is broken because JSON files cannot be opened in Python.",
        "d": "The file connects to a database.",
        "correct": "b",
        "explanation": "Imports and file operations tell a story. `import json` means JSON is involved. `open(\"data.json\")` means it reads or writes a file. You have understood the shape of the program before reading a single line of logic. This is how experienced developers read code.",
        "topic": "python",
        "difficulty": 2
    },

    # ===== PHASE 3: Extending the real app =====

    {
        "phase": 3,
        "text": "You add a route `@food_bp.route(\"/aboutme-test\")` to the food blueprint. What URL does it respond to?",
        "a": "/aboutme-test",
        "b": "/food/aboutme-test",
        "c": "/food_bp/aboutme-test",
        "d": "/aboutme-test/food",
        "correct": "b",
        "explanation": "Routes in a blueprint always get the blueprint's URL prefix prepended. The food blueprint is registered with `url_prefix=\"/food\"`, so any route inside it gets `/food` in front. `/aboutme-test` becomes `/food/aboutme-test`.",
        "topic": "flask",
        "difficulty": 1
    },
    {
        "phase": 3,
        "text": "What does `{% extends \"base.html\" %}` do in a Jinja2 template?",
        "a": "Copies the entire base.html file into your template.",
        "b": "Tells Flask to use base.html's layout (nav, style, structure) and let you fill in specific blocks.",
        "c": "Imports variables from base.html into your template.",
        "d": "Loads base.html in a separate frame on the page.",
        "correct": "b",
        "explanation": "Template inheritance means your template slots into base.html. The nav, CSS links, and overall layout come from base.html automatically. You only write what is different — your `{% block content %}`. This is why every page looks consistent without duplicating HTML.",
        "topic": "flask",
        "difficulty": 1
    },
    {
        "phase": 3,
        "text": "A form submits with `method=\"POST\"`. In your route you use `request.args.get(\"name\")` to read the submitted name. It returns None. Why?",
        "a": "The form field is named wrong in the HTML.",
        "b": "POST data is in `request.form`, not `request.args`. `request.args` reads URL query strings.",
        "c": "You need to convert args to a dict first.",
        "d": "POST requests do not send data at all.",
        "correct": "b",
        "explanation": "`request.args` reads from URL parameters like `/search?name={{LEARNER}}`. `request.form` reads from form body data (POST submissions). This mix-up is extremely common and causes None values that look like the data was never submitted.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 3,
        "text": "You add a route that queries the database and passes results to a template. The page loads but the list is empty even though data exists in the database. What is your first step?",
        "a": "Assume the CSS is hiding the results.",
        "b": "Add `print(results)` right after the DB query to confirm what the query actually returns.",
        "c": "Check that the template file is saved.",
        "d": "Restart Flask and try again.",
        "correct": "b",
        "explanation": "When data does not appear, always verify the data exists first before assuming it is a template problem. Print the query result to the terminal. If it prints empty, the bug is in the SQL query. If it has data, the bug is in the template. Diagnose before guessing.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 3,
        "text": "Your route does `return redirect(url_for(\"food.index\"))` after a POST. Why redirect instead of `render_template`?",
        "a": "`render_template` is significantly slower after a POST.",
        "b": "`redirect` is required by Flask's rules after any POST.",
        "c": "Redirecting prevents the user from resubmitting the form by refreshing the page.",
        "d": "`render_template` cannot be used in POST routes.",
        "correct": "c",
        "explanation": "If you render a template directly after a POST, the browser's refresh button re-submits the form — potentially inserting duplicate data. Redirecting sends the user to a GET request. Refreshing that is now safe. This pattern is called Post/Redirect/Get and is used throughout the family site.",
        "topic": "flask",
        "difficulty": 3
    },
    {
        "phase": 3,
        "text": "A Jinja2 `{% for item in items %}...{% endfor %}` loop runs with `items` being an empty list `[]`. What happens?",
        "a": "It crashes with an IndexError.",
        "b": "It outputs nothing — the loop body never runs.",
        "c": "It outputs one empty iteration.",
        "d": "It outputs the literal text 'items'.",
        "correct": "b",
        "explanation": "A for loop over an empty list simply does not run — zero iterations means zero output. If you want to show a message when the list is empty, add `{% else %}` inside the for loop. Jinja2 for loops support `{% for %}...{% else %}...{% endfor %}`.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 3,
        "text": "The family site's existing code saves data using `get_db()` and raw SQL. You are adding a new feature. Should you use this same pattern or install SQLAlchemy (an ORM)?",
        "a": "Install SQLAlchemy — it is always the better choice.",
        "b": "Use the same raw SQL pattern the site already uses.",
        "c": "Use JSON files since this is a small family site.",
        "d": "Use a completely different database for your feature.",
        "correct": "b",
        "explanation": "The curriculum rule: match the pattern the codebase already uses. Introducing SQLAlchemy creates inconsistency, adds a new dependency, and a steeper learning curve — for no benefit since the existing pattern works fine. Save architectural changes for a conversation with Dad.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 3,
        "text": "An HTMX button has `hx-post=\"/food/add-quick\"` and `hx-target=\"#result\"`. What happens when clicked?",
        "a": "The page navigates to /food/add-quick like a normal link.",
        "b": "A POST request is sent to /food/add-quick in the background, and whatever HTML it returns replaces the element with id='result'.",
        "c": "A GET request is sent and the entire page refreshes.",
        "d": "Nothing happens — hx-post requires a form element to work.",
        "correct": "b",
        "explanation": "HTMX intercepts the click, sends a background POST request without navigating away, and swaps the returned HTML into the element matching `hx-target`. The rest of the page is untouched. This is the core of how HTMX works.",
        "topic": "htmx",
        "difficulty": 2
    },
    {
        "phase": 3,
        "text": "You want to add a new page at `/aboutme/gallery`. You already have the aboutme blueprint registered. What is the minimum you need to add?",
        "a": "A new blueprint, a new template, and a new registration in app.py.",
        "b": "A new route function in the aboutme blueprint and a new template.",
        "c": "A new blueprint file for gallery, registered under /aboutme.",
        "d": "A new url_prefix entry in app.py.",
        "correct": "b",
        "explanation": "The blueprint already exists and is registered. Adding a route is just a new function with `@aboutme_bp.route(\"/gallery\")` plus its template. No new blueprint or app.py changes needed. That is the whole advantage of blueprints.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 3,
        "text": "In Jinja2, what is the difference between `{{ variable }}` and `{% statement %}`?",
        "a": "They are interchangeable — just different syntax for the same thing.",
        "b": "`{{ }}` outputs a value into the HTML. `{% %}` executes logic like loops and conditionals.",
        "c": "`{{ }}` is for Python expressions. `{% %}` is for HTML attributes.",
        "d": "`{{ }}` is safer because it escapes HTML. `{% %}` does not escape.",
        "correct": "b",
        "explanation": "`{{ current_user.username }}` renders the value — it gets replaced by the actual text. `{% for item in items %}` runs logic — it does not output itself, it controls what happens around it. Two different jobs, two different syntaxes.",
        "topic": "flask",
        "difficulty": 2
    },

    # ===== PHASE 4: Railway deployment =====

    {
        "phase": 4,
        "text": "You open the Railway dashboard for your project. Under Deployments, the latest build shows 'Success' but the live site still shows old content. What should you check first?",
        "a": "Whether the merge went to the branch Railway watches (usually `main`), not just a feature branch.",
        "b": "Whether Python is installed on your laptop.",
        "c": "Whether SQLite needs to be reinstalled.",
        "d": "Whether Cursor needs to be restarted.",
        "correct": "a",
        "explanation": "Railway deploys from the connected Git branch — typically `main`. A push to a feature branch updates GitHub but does not change production until the PR is merged. Always confirm which branch Railway is watching before assuming deploy failed.",
        "topic": "railway",
        "difficulty": 2
    },
    {
        "phase": 4,
        "text": "Railway runs your app with Gunicorn via the Procfile. Why does a new deploy replace the running code?",
        "a": "Gunicorn loads Python files into memory at startup — a new deploy starts a fresh process with the new code.",
        "b": "Railway clears the browser cache on every deploy.",
        "c": "GitHub automatically edits files on the server without restarting.",
        "d": "SQLite databases are rebuilt on every deploy.",
        "correct": "a",
        "explanation": "Gunicorn reads your Python code when the process starts. A Railway deploy builds new code and replaces the running container/process. The old in-memory code is gone when the new Gunicorn starts.",
        "topic": "railway",
        "difficulty": 2
    },
    {
        "phase": 4,
        "text": "You edit a file directly on the server instead of through git. Then you push a new commit from GitHub. What happens to the server edit?",
        "a": "The server edit is preserved because it was there first.",
        "b": "The git deploy overwrites it — the repo is the source of truth.",
        "c": "The deploy fails because of the conflict.",
        "d": "GitHub saves a backup of the server edit automatically.",
        "correct": "b",
        "explanation": "Deploys come from git. Anything not in the repo — including direct server edits — gets replaced on the next deploy. This is why the git-only deploy rule exists: if it is not in git, it will be lost.",
        "topic": "railway",
        "difficulty": 2
    },
    {
        "phase": 4,
        "text": "Your app stores SQLite files in `DATA_DIR`. On Railway, why must `DATA_DIR` point to a mounted volume (e.g. `/data`)?",
        "a": "Because Python cannot write files anywhere else.",
        "b": "Because the app filesystem without a volume is ephemeral — database files would be lost on redeploy.",
        "c": "Because Gunicorn only reads from `/data`.",
        "d": "Because GitHub requires volumes for all databases.",
        "correct": "b",
        "explanation": "Without a persistent volume, files written during runtime live on ephemeral disk and disappear when the container redeploys or restarts. Mount a volume at `/data`, set `DATA_DIR=/data`, and SQLite data survives deploys.",
        "topic": "railway",
        "difficulty": 2
    },
    {
        "phase": 4,
        "text": "You accidentally commit a local `auth.db` with only test users and deploy without excluding `*.db`. What happens on Railway if that file overwrites production data?",
        "a": "Nothing — Railway ignores database files automatically.",
        "b": "Production data could be replaced by your empty dev database — real users and records would be lost.",
        "c": "The deploy would fail because SQLite cannot run on Railway.",
        "d": "Railway creates a backup before overwriting.",
        "correct": "b",
        "explanation": "If your repo deploys a `.db` file and it lands on the volume, it can overwrite production data. Keep `*.db` in `.gitignore` and never commit database files. Production data should only exist on the Railway volume, created by the running app.",
        "topic": "railway",
        "difficulty": 2
    },
    {
        "phase": 4,
        "text": "You want to confirm your Railway service is healthy after a deploy. What is the fastest check built into this course's apps?",
        "a": "SSH into the server and run `ps aux`.",
        "b": "Visit `/healthz` — it should return `ok`.",
        "c": "Delete the Procfile and see if the build fails.",
        "d": "Run `nginx -t` on your laptop.",
        "correct": "b",
        "explanation": "Both the starter app and family site expose `GET /healthz` returning `ok`. Railway's healthcheck uses this path (see `railway.toml`). If `/healthz` works, Gunicorn is running and Flask responded.",
        "topic": "railway",
        "difficulty": 1
    },
    {
        "phase": 4,
        "text": "After your PR is merged and Railway shows deploy success, you visit the live site but your changes are not showing. What is the most likely cause?",
        "a": "DNS has not propagated yet.",
        "b": "Your browser is showing a cached version — try hard refresh with Ctrl+Shift+R.",
        "c": "Railway needs a separate Nginx restart.",
        "d": "Your change is on the wrong branch.",
        "correct": "b",
        "explanation": "Browsers cache aggressively. A normal refresh often serves the old cached version. Hard refresh (Ctrl+Shift+R) forces the browser to re-fetch everything from the server. This is the cause of probably 40% of 'my deploy did nothing' complaints.",
        "topic": "railway",
        "difficulty": 1
    },
    {
        "phase": 4,
        "text": "You open Railway runtime logs while clicking around your site. What are you looking for?",
        "a": "Proof that Python is installed on your laptop.",
        "b": "Request traces, errors, and tracebacks as the live app handles traffic.",
        "c": "Your git commit history.",
        "d": "The contents of your `.env` file.",
        "correct": "b",
        "explanation": "Runtime logs show what Gunicorn/Flask printed while serving requests — including tracebacks when something breaks. Build logs show the deploy; runtime logs show what happens when users hit the site. Read the error before asking the AI to fix it.",
        "topic": "railway",
        "difficulty": 2
    },
    {
        "phase": 4,
        "text": "Railway sets a `PORT` environment variable and your Procfile binds Gunicorn to `0.0.0.0:$PORT`. Why does this matter?",
        "a": "Gunicorn must listen on the port Railway routes public traffic to — a wrong port means the health check fails.",
        "b": "PORT controls how many Python files Gunicorn loads.",
        "c": "PORT is only used for local development.",
        "d": "PORT encrypts HTTPS automatically.",
        "correct": "a",
        "explanation": "Railway's proxy forwards HTTP to your service on `$PORT` (often 8080). If Gunicorn binds to the wrong port, nothing answers the health check and the deploy fails or the site stays down.",
        "topic": "railway",
        "difficulty": 2
    },
    {
        "phase": 4,
        "text": "You push a bug fix, Railway deploy succeeds, but the old bug still appears. Railway runtime logs still show the old code path. What is the most likely cause?",
        "a": "Git did not actually save your commit.",
        "b": "The fix was merged to a branch Railway is not watching, or the deploy is still rolling out.",
        "c": "Gunicorn cannot reload Python code without deleting the volume.",
        "d": "The user is visiting a different person's Railway project.",
        "correct": "b",
        "explanation": "If the merge did not land on the connected branch, Railway never built the fix. Also check you are visiting the correct project URL. Build logs show which commit deployed; runtime logs confirm which code path executed.",
        "topic": "railway",
        "difficulty": 2
    },

    # ===== PHASE 5: Security =====

    {
        "phase": 5,
        "text": "Your site uses HTTPS. A family member logs in while on a coffee shop's public WiFi. What is and is NOT protected?",
        "a": "Nothing is protected on public WiFi — always use a VPN.",
        "b": "The login password is protected in transit, but HTTPS does not protect against server-side vulnerabilities, XSS, or stolen session cookies.",
        "c": "Everything is protected — HTTPS makes websites completely secure.",
        "d": "Only the URL is protected, not the password or session.",
        "correct": "b",
        "explanation": "HTTPS encrypts data between the browser and server, so an eavesdropper on the coffee shop WiFi cannot read the password. But HTTPS does not protect against: bad password storage on the server, XSS attacks, stolen session cookies from malware, or bugs in the application code. HTTPS is one layer, not total security.",
        "topic": "security",
        "difficulty": 2
    },
    {
        "phase": 5,
        "text": "You accidentally commit your real `.env` file. You immediately delete it in the next commit and push. Is the SECRET_KEY safe?",
        "a": "Yes — the file is deleted so it is gone from GitHub.",
        "b": "No — it is still visible in git history. Anyone with repo access can see it with `git log -p`.",
        "c": "Yes — GitHub automatically scrubs secrets from commits.",
        "d": "Only if you force-push to overwrite the history.",
        "correct": "b",
        "explanation": "Git keeps every commit permanently. Deleting a file in a new commit does not remove it from history. `git log -p` shows the full diff of every commit, including the one where the secret was added. The secret must be rotated (changed to a new value) immediately, regardless of the deletion.",
        "topic": "security",
        "difficulty": 2
    },
    {
        "phase": 5,
        "text": "A user submits `<script>alert(\"hacked\")</script>` in a text input. Your route does `{{ user_input }}` in a Jinja2 template. What happens?",
        "a": "The script runs and shows an alert to every user who views the page.",
        "b": "Jinja2 escapes it automatically, so it displays as literal text instead of executing.",
        "c": "The server crashes with a SyntaxError.",
        "d": "Flask blocks the submission automatically before it reaches the template.",
        "correct": "b",
        "explanation": "Jinja2 auto-escapes `<`, `>`, `&` in `{{ }}` blocks, turning them into harmless HTML entities. `<script>` becomes `&lt;script&gt;` and renders as visible text, not code. This is why `{{ variable }}` is safe and `{{ variable | safe }}` is dangerous — only use `| safe` if you know exactly what the content is.",
        "topic": "security",
        "difficulty": 2
    },
    {
        "phase": 5,
        "text": "Your login route has no rate limiting. What attack does this make possible?",
        "a": "SQL injection on the username field.",
        "b": "XSS through the password field.",
        "c": "Brute force — an attacker can try thousands of passwords per second until one works.",
        "d": "CSRF — forging login requests from other sites.",
        "correct": "c",
        "explanation": "Without rate limiting, a script can try 'password1', 'password2', and so on at machine speed. Rate limiting blocks or slows requests after too many failures from the same IP, making brute force impractical. The family site does not have this yet — worth noting for Phase 5.",
        "topic": "security",
        "difficulty": 2
    },
    {
        "phase": 5,
        "text": "You call `generate_password_hash(\"mypassword\")` twice with the same password. Are the two resulting hashes identical?",
        "a": "Yes — the same input always produces the same hash.",
        "b": "No — werkzeug includes a random salt each time, so the same password hashes differently.",
        "c": "It depends on the SECRET_KEY setting.",
        "d": "Yes, but only if you specify SHA-256 explicitly.",
        "correct": "b",
        "explanation": "Secure password hashing adds a random 'salt' to the password before hashing. Same password, different salt, different hash every time. `check_password_hash` knows how to verify correctly despite this. If hashes were identical, an attacker could build a lookup table of all common passwords and crack the whole database at once.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 5,
        "text": "A Flask route builds a SQL query like this: `f\"SELECT * FROM users WHERE name = '{name}'\"` where `name` comes from a form field. What is wrong?",
        "a": "You should use `SELECT name` not `SELECT *`.",
        "b": "SQL queries cannot use f-strings — only string concatenation.",
        "c": "A user can enter `'; DROP TABLE users; --` as their name and delete the database.",
        "d": "Nothing — f-strings are the recommended way to build SQL queries.",
        "correct": "c",
        "explanation": "SQL injection. The user's input becomes part of the SQL command. An attacker enters crafted SQL as their 'name' and it executes. The fix is parameterized queries: `'SELECT * FROM users WHERE name = ?'` with `(name,)` as a separate argument to `cursor.execute()`. The family site already does this correctly everywhere — never change it.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 5,
        "text": "The site stores sessions in a signed cookie using SECRET_KEY. What can an attacker do if they learn the SECRET_KEY?",
        "a": "Read your session data but cannot modify it.",
        "b": "Forge any session cookie, appearing as any user including admins.",
        "c": "Decrypt your HTTPS traffic.",
        "d": "Gain SSH access to the server.",
        "correct": "b",
        "explanation": "Session cookies are signed with SECRET_KEY to prevent tampering. If an attacker has the key, they can forge a valid signature on any session data — like `{\"user_id\": 1, \"is_admin\": true}`. They become any user they want. This is why the key must be long, random, and never in git.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 5,
        "text": "`.gitignore` lists `.env`. You run `git add .env` explicitly. What happens?",
        "a": "Git refuses — .gitignore blocks all attempts to add the file.",
        "b": "Git warns you but stages the file anyway.",
        "c": "The file gets staged silently without any warning.",
        "d": ".gitignore only applies to `git add .`, not to explicitly named files.",
        "correct": "b",
        "explanation": "`.gitignore` prevents files from being accidentally staged by `git add .`. But if you explicitly name the file, git stages it regardless and shows a warning. The ignore is a safety net, not a hard block. This is one of the most common ways secrets end up on GitHub.",
        "topic": "security",
        "difficulty": 2
    },
    {
        "phase": 5,
        "text": "You are writing a threat model for the family site. Who is the most realistic attacker, and what do they actually want?",
        "a": "A nation-state looking to access family photos for surveillance.",
        "b": "An automated bot scanning for common vulnerabilities to exploit for spam or crypto mining.",
        "c": "A competitor trying to steal the recipe database.",
        "d": "A family member trying to access other family members' accounts.",
        "correct": "b",
        "explanation": "Most attacks on small sites are automated, not targeted. Bots scan millions of sites looking for unpatched software, default credentials, or upload vulnerabilities they can exploit for spam or crypto mining. They do not care whose site it is. This is why keeping dependencies updated and not using default passwords matters even for a family site.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 5,
        "text": "You add a profile picture upload feature. Which of these is a genuine security concern beyond just file size?",
        "a": "Users uploading pictures of themselves.",
        "b": "A user uploading a `.py` file that gets served incorrectly and executes as Python.",
        "c": "Photos being too high resolution.",
        "d": "Users uploading images from phones instead of computers.",
        "correct": "b",
        "explanation": "File upload security requires validating the extension AND content type. The site already has an allowed extensions whitelist (jpg, jpeg, png, gif, webp) — this exists for exactly this reason. Never remove it. An attacker uploading a script file that gets served and executed by the server is a real attack called malicious file upload.",
        "topic": "security",
        "difficulty": 2
    },

    # ===== PHASE 6: Capstone =====

    {
        "phase": 6,
        "text": "You push your capstone feature and the live site shows a 500 error. You cannot SSH in right now. What is your best source of diagnostic information?",
        "a": "Re-read your source code looking for the bug.",
        "b": "Check the GitHub Actions logs for the deploy output and any startup errors.",
        "c": "Ask Dad to look at the server immediately.",
        "d": "Roll back the commit and try again without debugging.",
        "correct": "b",
        "explanation": "GitHub Actions logs show the full deploy output including any Python tracebacks from startup. If the app crashed on startup, the traceback is there. Always check logs before guessing at the cause — it is usually faster.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 6,
        "text": "Your form accepts a name field. A user submits it empty. What is the correct way to handle this?",
        "a": "`name = request.form[\"name\"]` — Flask raises an error automatically if it is missing.",
        "b": "`name = request.form.get(\"name\")` then check `if not name` and return an error message.",
        "c": "Add `required` to the HTML input — that is sufficient validation.",
        "d": "Wrap it in try/except and set name to an empty string if it fails.",
        "correct": "b",
        "explanation": "`request.form.get(\"name\")` returns None (not an error) when the field is empty or missing. You then check `if not name` to catch both None and empty string. `required` in HTML is easily bypassed — never trust client-side validation alone. Server-side validation is mandatory.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 6,
        "text": "Your feature works perfectly locally but throws a 500 on the live site. The deploy log shows no errors. What are the three most likely causes?",
        "a": "Browser cache, screen resolution, and internet speed.",
        "b": "Missing environment variables on the server, database schema differences, or a Python package version mismatch.",
        "c": "Git commit message format, CSS file permissions, and Nginx config.",
        "d": "DNS settings, SSL certificate expiry, and GitHub Actions version.",
        "correct": "b",
        "explanation": "The most common local/production mismatches: (1) An env variable exists in your `.env` but was not added to the server's `.env`. (2) You added a database column locally but never added it in production. (3) A package version behaves differently. These three cover the vast majority of 'works locally' bugs.",
        "topic": "flask",
        "difficulty": 3
    },
    {
        "phase": 6,
        "text": "Which git commit message is best?",
        "a": "fix bug",
        "b": "updated files",
        "c": "fix crash when recipe title is empty — title was not validated before DB insert",
        "d": "WIP trying stuff",
        "correct": "c",
        "explanation": "Good commit messages say what changed AND why. Someone reading git history months later should understand the reason without reading the diff. 'fix bug' tells you nothing. 'fix crash when recipe title is empty — title was not validated before DB insert' tells you exactly what broke and what the fix was.",
        "topic": "git",
        "difficulty": 1
    },
    {
        "phase": 6,
        "text": "You want to add a guestbook feature requiring a new database table. What is the correct order of steps?",
        "a": "Write the template → add the route → create the database table → test.",
        "b": "Create the database table → add the route → write the template → test.",
        "c": "Test first → template → route → database.",
        "d": "Add the route → write the template → create the database table → test.",
        "correct": "b",
        "explanation": "Each layer depends on the one below it. The database must exist before the route can query it. The route must exist before the template can submit to it. Build bottom-up: data layer first, then business logic, then presentation. This order means each layer has what it needs when you build the next.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 6,
        "text": "You review your own code before opening a PR. You find this:\n```\nitems = get_all_items()\nprint(items[0])\n```\nWhat is the problem?",
        "a": "`get_all_items()` is not a valid function name.",
        "b": "`print` should be `return`.",
        "c": "If the database is empty, `items[0]` will crash with an IndexError.",
        "d": "You need to close the database connection after `get_all_items()`.",
        "correct": "c",
        "explanation": "Indexing into a list without checking if it is empty first is one of the most common bugs in production code. If `items` is `[]`, `items[0]` raises an IndexError and your page crashes. Always check `if items:` before indexing, or use `items[0] if items else None`.",
        "topic": "python",
        "difficulty": 2
    },
    {
        "phase": 6,
        "text": "A family member reports that submitting your guestbook form twice shows their message twice. What is causing this?",
        "a": "There is a bug in the database insert function.",
        "b": "The route renders a template directly after POST instead of redirecting. Refreshing re-submits the form.",
        "c": "The browser is malfunctioning.",
        "d": "The route is missing `@login_required`.",
        "correct": "b",
        "explanation": "If you `render_template` after a POST, the browser's refresh button re-sends the POST, inserting a second record. Post/Redirect/Get fixes this: after saving, call `redirect()` to a GET route. Refresh now re-runs the GET, which is always safe.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 6,
        "text": "You are walking Dad through your capstone. You get to one file and genuinely cannot explain what line 15 does. According to the curriculum, what happens?",
        "a": "You skip it and explain the rest.",
        "b": "Dad explains it to you and you move on.",
        "c": "That line is removed or rewritten until you can explain it, before you graduate.",
        "d": "You look it up in the documentation and read the explanation aloud.",
        "correct": "c",
        "explanation": "The graduation criterion from the curriculum: you can explain every single line. A line you cannot explain is a line you do not own. If it is in your project, it needs to be understood or removed. This is the explain rule — the single most important rule of the entire course.",
        "topic": "python",
        "difficulty": 1
    },
    {
        "phase": 6,
        "text": "A family member submits a message that is 10,000 characters long and it breaks the page layout. What should you have done during development to catch this?",
        "a": "Added JavaScript to prevent long input on the form.",
        "b": "Tested edge cases: empty input, very long input, special characters like emoji and angle brackets.",
        "c": "Made the database column larger.",
        "d": "Added a loading spinner to handle slow submissions.",
        "correct": "b",
        "explanation": "Edge case testing asks: what is the weirdest thing a real user might do? Empty = nothing submitted. Very long = too much. Special characters = might break HTML or SQL. These three cover most real-world breakage. Testing only the happy path is not sufficient.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 6,
        "text": "You have completed all 6 phases. Looking back, what is the single most transferable skill you developed?",
        "a": "Memorizing Python syntax.",
        "b": "Typing speed.",
        "c": "Reading error messages, understanding what they mean, and finding the fix yourself.",
        "d": "Knowing when to ask for help.",
        "correct": "c",
        "explanation": "Syntax is lookupable. Frameworks change. The skill that transfers to every language, every tool, and every job is: read the error, understand what it is telling you, and figure out the fix. That is what separates someone who codes with AI from someone who actually knows how to build things.",
        "topic": "python",
        "difficulty": 1
    },

    # ===== SYNTHESIS (phase=0): Final test only — cross-phase integration =====

    {
        "phase": 0,
        "text": "You are on a feature branch with committed but unpushed changes. The live site has a critical bug that needs a hotfix immediately. What is the correct process?",
        "a": "Push your feature branch and fix the bug there.",
        "b": "Stash or commit your work, switch to master, fix the bug on a new hotfix branch, PR it, then return to your feature branch.",
        "c": "Delete your feature branch and start over after the hotfix.",
        "d": "Fix the bug directly on the server to save time.",
        "correct": "b",
        "explanation": "Never mix a hotfix into a feature branch — they are unrelated changes. Stash your work (`git stash`), switch to master, create a hotfix branch, fix it, PR it. Then return to your feature branch and `git stash pop`. Direct server edits violate the droplet rule and get overwritten by the next deploy.",
        "topic": "git",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "A route needs to be admin-only. Which implementation is correct?",
        "a": "Add `if current_user.is_admin` inside the template only.",
        "b": "Add an `if not current_user.is_admin: return redirect('/')` check at the top of the route function.",
        "c": "Use the `@admin_required` decorator the site already defines.",
        "d": "Both B and C are correct, but C is better because it is reusable.",
        "correct": "d",
        "explanation": "B works but duplicates logic every time. C uses the existing decorator which the admin blueprint already defines — exactly what 'this codebase's pattern' means. Template-only checks (A) are dangerous because the route itself is still accessible. Always protect at the route level, not just the template.",
        "topic": "flask",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "Your route does `name = request.form[\"name\"].upper()`. Users sometimes leave the field blank. What happens and how do you fix it?",
        "a": "Returns an empty string. No fix needed.",
        "b": "Raises a KeyError if the field is missing entirely. Use `request.form.get(\"name\", \"\")` then check if blank.",
        "c": "Crashes with AttributeError because you cannot call `.upper()` on None. Use `.get()` and check before calling `.upper()`.",
        "d": "Both B and C depending on whether the field exists in the form at all.",
        "correct": "d",
        "explanation": "If the HTML field exists but is empty, `request.form[\"name\"]` returns `\"\"` and `.upper()` works fine but gives `\"\"`. If the field is missing from the form entirely (e.g., bypassed), it raises a KeyError. Defensive code handles both: `name = request.form.get(\"name\", \"\").strip()` then `if not name: return error`.",
        "topic": "flask",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "You push a fix but the server logs show the old code path is still executing. The GitHub Actions deploy shows 'success'. Walk through your diagnosis in order.",
        "a": "Check git history → check branch → check server files → check process.",
        "b": "Check deploy log for the `systemctl restart` step → check `systemctl status family-site` → if still old code, restart manually and check for errors.",
        "c": "Re-push the same commit → wait 5 minutes → hard refresh the browser.",
        "d": "Rollback the deploy and try again.",
        "correct": "b",
        "explanation": "If files deployed but behavior did not change, Gunicorn is the most likely culprit — it loaded the old code and the restart either failed or was skipped. Check the deploy log for the restart step. Then check service status. If it is running the old code, a manual restart reveals the real error (often a Python startup crash in the new code).",
        "topic": "linux",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "You are building a form that accepts a user's bio. You want to allow basic HTML like `<b>` and `<i>`. What is the security risk and how should you handle it?",
        "a": "No risk — Jinja2 handles this automatically.",
        "b": "XSS risk. You must sanitize the input to allow only safe tags before storing or rendering with `| safe`.",
        "c": "SQL injection risk. Use parameterized queries.",
        "d": "No risk as long as you use `request.form.get()` instead of `request.form[]`.",
        "correct": "b",
        "explanation": "Allowing any HTML and rendering with `| safe` is XSS. A user could submit `<script>steal_cookies()</script>`. You need a sanitization library (like bleach) that allows only a specific whitelist of tags. This is genuinely hard to do correctly — for a family site, the safer choice is to disallow HTML entirely and use `{{ bio }}` with auto-escaping.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "You query the database with `db.execute('SELECT * FROM items').fetchall()`. The result is a list of `sqlite3.Row` objects. How do you access the `title` field of the first row?",
        "a": "result[0][0]",
        "b": "result[0].title",
        "c": "result[0]['title']",
        "d": "Both B and C work because sqlite3.Row supports both syntaxes.",
        "correct": "d",
        "explanation": "When `db.row_factory = sqlite3.Row` is set (which the family site does in every blueprint), rows support both `row['title']` (dict-style) and `row.title` (attribute-style) access. Both work. The codebase mostly uses `row['column']` style, so match that for consistency.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "Dad reviews your PR and asks for changes before merging. What are your git steps?",
        "a": "Close the PR, make changes on master, open a new PR.",
        "b": "Make the changes locally on the same branch, commit them, and push — the PR updates automatically.",
        "c": "Create a new branch from your feature branch, make changes there, and merge it back.",
        "d": "Make changes locally and push with `--force` to overwrite.",
        "correct": "b",
        "explanation": "A PR tracks a branch, not a specific set of commits. Any new commits you push to that branch automatically appear in the open PR. Just make the changes, `git commit`, `git push` — Dad sees the updates immediately. No need to close or reopen anything.",
        "topic": "git",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "An `hx-get=\"/aboutme/refresh\"` attribute is on a `<div>`. The route returns `<p>Hello</p>`. Where does that HTML end up if there is no `hx-target` specified?",
        "a": "It replaces the entire page body.",
        "b": "It is discarded — hx-target is required.",
        "c": "It replaces the content of the element that has the hx-get attribute (the div itself).",
        "d": "It appends to the bottom of the page.",
        "correct": "c",
        "explanation": "When no `hx-target` is specified, HTMX defaults to swapping the content of the element that triggered the request. The div's inner HTML gets replaced with `<p>Hello</p>`. Use `hx-target` to send the response somewhere else, and `hx-swap` to control whether it replaces, appends, etc.",
        "topic": "htmx",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "You realize you committed a test database file containing fake passwords to git and pushed it. What do you do?",
        "a": "Delete the file in a new commit — that is sufficient.",
        "b": "Nothing — they are fake passwords so there is no risk.",
        "c": "Remove the file from git history using `git filter-branch` or BFG Repo Cleaner, force-push, then ensure .gitignore is correct going forward.",
        "d": "Make the GitHub repository private.",
        "correct": "c",
        "explanation": "Even fake passwords in git are bad practice and teach bad habits. Deleting in a new commit leaves the data in history. The correct fix is to purge it from git history entirely. For real secrets this is critical — even if you rotate them, scrubbing history is best practice. Then fix .gitignore so it cannot happen again.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "Your feature fails in production with `KeyError: 'NEW_FEATURE_KEY'` but works locally. What is the cause and fix?",
        "a": "The Python version on the server is different.",
        "b": "A new environment variable exists in your local `.env` but was never added to the `.env` on the server.",
        "c": "The GitHub Actions runner is out of date.",
        "d": "The key needs to be added to `requirements.txt`.",
        "correct": "b",
        "explanation": "This is the most common cause of production KeyErrors. You added a new variable to your local `.env`, used it in code, tested locally (it works), pushed, and deployed — but the server's `.env` does not have the new variable. Fix: SSH in (or ask Dad to), add the variable to the server's `.env`, restart the service.",
        "topic": "linux",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "How do you correctly handle a form value that should be an integer but might not be?",
        "a": "Just call `int(request.form.get('age'))` — Flask validates types automatically.",
        "b": "Use `int(request.form.get('age', 0))` — the default 0 prevents crashes.",
        "c": "Wrap in try/except: get the value, attempt `int()`, return a user-facing error if it raises ValueError.",
        "d": "Add `type='number'` to the HTML input — browsers enforce it.",
        "correct": "c",
        "explanation": "`int('abc')` raises ValueError. `int(None)` raises TypeError. HTML type attributes are client-side only and easily bypassed. Defensive server-side validation: get the raw string, attempt conversion in a try/except, and return a meaningful error to the user if it fails. Never trust what arrives from a form.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "A Jinja2 template has `{% if items %}{{ items[0].title }}{% else %}<p>No items.</p>{% endif %}`. When does the else block show?",
        "a": "When items is None.",
        "b": "When items is an empty list [].",
        "c": "When items is None or an empty list — both are falsy.",
        "d": "Never — you must use `{% if items | length == 0 %}`.",
        "correct": "c",
        "explanation": "In Python (and Jinja2), `None`, `[]`, `{}`, `\"\"`, and `0` are all falsy. `{% if items %}` is False for both None and an empty list. This is actually useful — you can check 'does this have content' without knowing whether it might be None or empty.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "You need to update the server's `.env` file with a new secret. Why can you NOT just push the `.env` to GitHub to deploy it?",
        "a": "GitHub does not support `.env` files.",
        "b": ".env is in `.gitignore` and should never be committed — secrets in git are permanently exposed. SSH in to edit it directly on the server.",
        "c": "The deploy workflow does not copy `.env` files.",
        "d": "Both B and C — .env should not be in git, and the workflow explicitly excludes it.",
        "correct": "d",
        "explanation": "Secrets must never go through git. Even in a private repo, a leaked token, a compromised account, or a future public fork could expose them. The workflow explicitly excludes `.env` from rsync. Update server secrets by SSHing in and editing the file directly — or using a proper secrets manager. Both reasons apply.",
        "topic": "security",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "You accidentally committed to `master` instead of a feature branch. You have NOT pushed yet. How do you fix it?",
        "a": "Nothing you can do — the commit is permanent.",
        "b": "Create the feature branch now: `git checkout -b feature-name`. The commit moves with you since HEAD moves.",
        "c": "`git reset HEAD~1` to undo the commit, then create your branch and recommit.",
        "d": "Both B and C work. B is faster; C is more explicit.",
        "correct": "d",
        "explanation": "B works because creating a new branch from the current HEAD takes all commits including the accidental one. C works by undoing the commit (keeping changes), then re-doing it on the right branch. Both are valid. The key constraint: you have not pushed yet, so both are safe. Once pushed, fixing it is harder.",
        "topic": "git",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "When would you use a list vs a dict to store family member data?",
        "a": "Always use a list — dicts are only for configuration.",
        "b": "List when you just need ordered names. Dict when you need to look up data by name or store multiple fields per person.",
        "c": "Always use a dict — lists are slower.",
        "d": "List for fewer than 10 items, dict for more.",
        "correct": "b",
        "explanation": "`['{{LEARNER}}', 'Dad', 'Mom']` is fine if you only need to loop through names. `{'{{LEARNER}}': {'age': 13, 'role': 'daughter'}}` is better when you need to look someone up by name or store multiple attributes. Choose the structure that matches what you will do with the data.",
        "topic": "python",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "`url_for('food.index')` in a Jinja2 template generates what URL?",
        "a": "/food_bp/index",
        "b": "Whatever URL the `index` function inside the `food` blueprint is registered to handle.",
        "c": "/food/index",
        "d": "The URL only works if there is a route literally named 'index'.",
        "correct": "b",
        "explanation": "`url_for` generates the URL for a named route. `'food.index'` means the function named `index` in the `food` blueprint. If that function is decorated with `@food_bp.route('/')`, the generated URL is `/food/`. It adapts automatically if you change the route path — which is why `url_for` is always better than hardcoding `/food/`.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "Show the correct way to write a SQLite parameterized query that finds a recipe by ID.",
        "a": "db.execute(f'SELECT * FROM recipes WHERE id = {recipe_id}')",
        "b": "db.execute('SELECT * FROM recipes WHERE id = ' + str(recipe_id))",
        "c": "db.execute('SELECT * FROM recipes WHERE id = ?', (recipe_id,))",
        "d": "db.execute('SELECT * FROM recipes WHERE id = :id', recipe_id)",
        "correct": "c",
        "explanation": "Option C is the correct parameterized query syntax for sqlite3. The `?` is a placeholder, and `(recipe_id,)` is a tuple of values. The trailing comma makes it a tuple (not just parentheses). Options A and B build the SQL by concatenation — SQL injection vulnerabilities. The family site uses this pattern throughout.",
        "topic": "security",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "The deploy workflow excludes `static/uploads/`. Why?",
        "a": "Uploaded files are too large to transfer efficiently.",
        "b": "User-uploaded photos live on the server and should not be overwritten by deploys — they are not in the git repo.",
        "c": "Static files do not need to be deployed.",
        "d": "GitHub does not allow binary file storage.",
        "correct": "b",
        "explanation": "Family photos are uploaded by users directly to the server. They are not tracked in git (also in .gitignore). If rsync did not exclude `static/uploads/`, deploying would delete all family photos from the server. The uploads folder is treated as persistent server data, like the databases.",
        "topic": "linux",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "Every page on the family site shares the same nav, CSS, and layout without duplicating HTML. How is this achieved?",
        "a": "Flask automatically generates nav HTML for all pages.",
        "b": "Each template imports a nav component using JavaScript.",
        "c": "Every template extends `base.html` using Jinja2 template inheritance.",
        "d": "Nginx injects the nav before serving each page.",
        "correct": "c",
        "explanation": "`{% extends 'base.html' %}` at the top of every template means the page inherits base.html's complete structure. You only write the parts that differ in `{% block content %}`. Change base.html once and every page updates. This is one of the most important patterns in Flask.",
        "topic": "flask",
        "difficulty": 1
    },
    {
        "phase": 0,
        "text": "Your function is supposed to return a value but you see `None` when you print the result. What are three plausible causes?",
        "a": "The function is named wrong, the import failed, and Python is broken.",
        "b": "Missing `return` statement, `return` is inside a conditional that did not trigger, or the function returned early before the value was computed.",
        "c": "The variable type is wrong, the database is empty, and the template has a bug.",
        "d": "The function runs but Python discards the return value automatically.",
        "correct": "b",
        "explanation": "The three most common causes of unexpected None: (1) Forgot `return result` at the end. (2) `return result` is inside `if something:` but `something` was False. (3) The function returned early via an `if` branch before reaching the return. Check all exit paths of the function.",
        "topic": "python",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "You and Dad both edit `app.py`. He pushes first. What happens when you try to push?",
        "a": "Your push succeeds and overwrites his changes.",
        "b": "Git rejects your push and tells you to pull first, then merge.",
        "c": "GitHub automatically merges the two versions.",
        "d": "Your push fails permanently until you create a new branch.",
        "correct": "b",
        "explanation": "Git rejects non-fast-forward pushes to protect against overwriting others' work. You need to `git pull` first, which fetches his changes and attempts to merge them with yours. If you both edited different parts of `app.py`, git merges automatically. If you edited the same lines, you get a merge conflict to resolve.",
        "topic": "git",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "Why does the family site use separate `.db` files for each blueprint instead of one shared database?",
        "a": "SQLite cannot handle multiple tables in one file.",
        "b": "Each blueprint is more independent — it owns its own data, reducing coupling between features.",
        "c": "Multiple database files is required by Flask's blueprint architecture.",
        "d": "It is easier to back up separate files.",
        "correct": "b",
        "explanation": "This is an architectural choice for modularity. Each blueprint manages its own data and does not depend on other blueprints' tables (except where explicitly queried, like calendar reading from recipes.db). The tradeoff is you cannot do cross-blueprint SQL joins easily — but for this site that is acceptable.",
        "topic": "flask",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "Flask's session cookie has `SESSION_COOKIE_HTTPONLY = True` set. What specific attack does this mitigate?",
        "a": "SQL injection via the session cookie.",
        "b": "JavaScript on the page reading the session cookie (used in XSS attacks to steal sessions).",
        "c": "The session cookie being sent over HTTP instead of HTTPS.",
        "d": "Forged session cookies from attackers.",
        "correct": "b",
        "explanation": "HttpOnly means the cookie cannot be accessed by JavaScript — `document.cookie` will not show it. This is specifically to mitigate XSS: even if an attacker injects JavaScript into your page, they cannot steal the session cookie. They can still do damage with injected JS, but stealing the session for account takeover becomes much harder.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "The GitHub Actions runner is installed as a service on the VPS. Why does `sudo systemctl restart family-site` work in the workflow without a password prompt?",
        "a": "The runner runs as root.",
        "b": "The runner user has been granted passwordless sudo specifically for the `systemctl restart family-site` command via sudoers.",
        "c": "GitHub Actions automatically has root access on self-hosted runners.",
        "d": "systemctl does not require sudo on Ubuntu.",
        "correct": "b",
        "explanation": "The server is configured with a sudoers rule allowing the runner's user to run exactly `systemctl restart family-site` without a password. This is the principle of least privilege: the runner gets only the minimum permissions needed, not full root access. Granting full passwordless sudo to a CI runner would be a significant security risk.",
        "topic": "linux",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "What is the practical difference between defining a function that modifies a global variable vs one that takes parameters and returns a value?",
        "a": "No difference — both approaches produce the same result.",
        "b": "Functions with parameters and returns are testable, reusable, and have no hidden side effects. Global-modifying functions are harder to reason about and debug.",
        "c": "Global variable functions are faster because they skip parameter passing.",
        "d": "You should always use global variables for database connections.",
        "correct": "b",
        "explanation": "A function that modifies globals has hidden dependencies — it is hard to know what it changes without reading the whole function. A function that takes inputs and returns outputs is self-contained: you know exactly what goes in and what comes out. This makes it testable and reusable. The family site database functions follow the return-value pattern for exactly this reason.",
        "topic": "python",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "A route queries the database for a record by ID from a URL parameter: `/recipe/999`. The ID does not exist. What should the route return?",
        "a": "An empty page.",
        "b": "A 500 Internal Server Error.",
        "c": "A 404 Not Found response, either with Flask's `abort(404)` or by returning a 404 template.",
        "d": "A redirect to the recipe list.",
        "correct": "c",
        "explanation": "404 is semantically correct: the resource does not exist. `abort(404)` raises a 404 immediately. Returning a 500 would be misleading (nothing is broken). An empty page is confusing to the user. A redirect to the list is acceptable UX but hides the fact that the URL was invalid. Flask has `abort(404)` specifically for this case.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "An HTMX route must return partial HTML rather than a full page. Why does returning a full rendered template with `{% extends 'base.html' %}` cause problems?",
        "a": "Flask does not allow render_template in HTMX routes.",
        "b": "HTMX injects the response HTML into a specific element — a full page response would inject a second nav, head, and body inside that element.",
        "c": "HTMX only accepts JSON responses, not HTML.",
        "d": "The base template is too large and causes a timeout.",
        "correct": "b",
        "explanation": "HTMX swaps the route's response HTML into a DOM element. If you return a full `base.html` page, the nav, head tags, and body all get injected inside whatever div you targeted — you end up with a page-inside-a-page. HTMX routes should return only the fragment of HTML needed for the swap.",
        "topic": "htmx",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "You are reviewing your capstone before demo night. You find a variable named `x` in a function. What should you do?",
        "a": "Leave it — single-letter variable names are standard in Python.",
        "b": "Rename it to something descriptive that explains what it holds.",
        "c": "Add a comment explaining what x is.",
        "d": "Only rename it if the function is longer than 10 lines.",
        "correct": "b",
        "explanation": "The graduation criterion is that you can explain every line. A variable named `x` makes the code harder to explain — you have to remember what it means. `recipe_count` or `user_age` is self-documenting. Code should be readable without needing a comment to explain what a variable is. Rename it.",
        "topic": "python",
        "difficulty": 1
    },
    {
        "phase": 0,
        "text": "A family member clicks a button on your feature and nothing happens — no error, no response, just silence. Walk through the layers you would check.",
        "a": "CSS → HTML → JavaScript → Flask route → database",
        "b": "Browser console for JS errors → Network tab to see if a request was sent → Flask logs to see if the route received the request → route logic → database query",
        "c": "Database → Flask route → template → browser",
        "d": "Git log → deploy log → server status → browser refresh",
        "correct": "b",
        "explanation": "Start where the user is (browser) and work inward. Browser console shows JS errors that would prevent a request from being sent. Network tab shows whether the request reached the server. Flask logs show whether the route executed. Route logic shows whether data was processed. Database shows whether data was saved. Always follow the request through the full stack.",
        "topic": "flask",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "What is the correct way to serve user-uploaded files securely in Flask?",
        "a": "Put uploads in the `static/` folder and link to them directly.",
        "b": "Create a route that checks `@login_required`, finds the file by a safe path, and sends it with `send_from_directory`.",
        "c": "Configure Nginx to serve the uploads folder publicly.",
        "d": "Store file contents in the database as base64.",
        "correct": "b",
        "explanation": "The family site does this correctly — `/photos/file/<path>` requires login and uses `send_from_directory` with the uploads folder as the base. This prevents path traversal attacks (someone requesting `../../etc/passwd`) and keeps uploads behind authentication. Serving from `static/` directly would expose files to anyone with the URL.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "`git log --oneline` shows your recent commits. Why does this matter when something breaks in production?",
        "a": "It tells you which files were changed in each commit.",
        "b": "It lets you identify which commit introduced the bug and revert specifically to before it.",
        "c": "It shows who deployed last.",
        "d": "It is required before running git push.",
        "correct": "b",
        "explanation": "Good commit history is a debugging tool. When production breaks, `git log` shows you every recent change. Meaningful commit messages let you identify the likely culprit without reading every diff. You can then `git revert <hash>` to undo a specific commit cleanly, or `git show <hash>` to see exactly what changed. This is why commit messages matter.",
        "topic": "git",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "The site has a valid Let's Encrypt SSL certificate. What does this certificate prove to visitors?",
        "a": "The site's code has been security-audited.",
        "b": "The server at this domain is controlled by someone who had access to configure DNS or the web server at the time the certificate was issued.",
        "c": "All data on the site is encrypted at rest.",
        "d": "The site cannot be hacked.",
        "correct": "b",
        "explanation": "An SSL certificate proves domain control at the time of issuance — that whoever set it up controlled the domain. It enables encrypted transit (HTTPS). It does NOT prove the site is secure, the code is bug-free, or data is stored safely. It is one important layer, not total security.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "`open('data.json')` works locally but raises `FileNotFoundError` in production. What is the most likely reason?",
        "a": "The Python version on the server is different.",
        "b": "The file path is relative — it resolves relative to the working directory, which differs between local and production.",
        "c": "JSON files are not supported on Linux.",
        "d": "The file needs to be in `requirements.txt`.",
        "correct": "b",
        "explanation": "Relative paths like `'data.json'` resolve relative to the current working directory when the script runs. Locally that might be the project root. On the server (run by systemd), the working directory could be different. Fix: use `os.path.join(os.path.dirname(__file__), 'data.json')` to build an absolute path relative to the script file.",
        "topic": "python",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "After a user logs out, why is it important to call `logout_user()` rather than just deleting a cookie client-side?",
        "a": "Deleting a cookie is impossible from Python.",
        "b": "`logout_user()` invalidates the server-side session so stolen session data cannot be reused, and clears the cookie properly.",
        "c": "Cookies are automatically deleted after 30 minutes anyway.",
        "d": "No difference — either method achieves the same result.",
        "correct": "b",
        "explanation": "`logout_user()` from Flask-Login clears the server-side session and instructs the browser to delete the cookie. Simply deleting the cookie client-side (via JavaScript) leaves the session data on the server — if someone has a copy of the cookie (e.g., from a screenshot or network capture), they could still use it. Server-side logout is the authoritative action.",
        "topic": "security",
        "difficulty": 3
    },
    {
        "phase": 0,
        "text": "What is the advantage of GitHub Actions deploying automatically over manually SSH-ing in each time?",
        "a": "GitHub Actions is faster than SSH.",
        "b": "Automation removes human error, ensures every deploy follows the same steps, creates an audit log of all deploys, and means anyone can ship by merging a PR.",
        "c": "GitHub Actions has admin access to the server.",
        "d": "Manual SSH deploys are not allowed on most servers.",
        "correct": "b",
        "explanation": "Manual deploys have failure modes: you might forget a step, deploy the wrong branch, or skip restarting the service. Automation ensures the same process runs every time. The GitHub Actions log also gives you a record of every deploy — who triggered it, what ran, whether it succeeded. This is standard industry practice.",
        "topic": "linux",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "A variable defined inside an `if` block in Python — is it accessible after the block ends?",
        "a": "No — Python uses block scope like JavaScript.",
        "b": "Yes — Python uses function scope. Variables defined anywhere in a function exist for the rest of that function.",
        "c": "Only if the `if` condition was True.",
        "d": "Only if the variable was declared before the `if` block.",
        "correct": "b",
        "explanation": "Python does not have block scope. A variable defined inside `if`, `for`, `while`, or `with` blocks is accessible for the rest of the enclosing function. This is different from JavaScript and C. The danger: if the `if` branch did not execute, the variable is undefined and accessing it raises a NameError.",
        "topic": "python",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "A form has `method=\"GET\"` instead of `method=\"POST\"`. What is different about where the form data goes?",
        "a": "GET forms do not send any data.",
        "b": "GET form data appears in the URL as query parameters (visible, bookmarkable, cached). POST data is in the request body (not in the URL).",
        "c": "GET forms require `request.form`. POST forms require `request.args`.",
        "d": "GET and POST send data identically — the method only affects caching.",
        "correct": "b",
        "explanation": "GET appends data to the URL: `/search?q=chicken+recipes`. This is fine for searches (bookmarkable, shareable). POST sends data in the request body — not visible in the URL. Use POST for actions that change data (submitting a form, creating a record) and GET for fetching/searching. Never send passwords or sensitive data via GET.",
        "topic": "flask",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "The site's current SECRET_KEY in `.env.example` is `change-me-to-a-long-random-string`. What should it actually be and why?",
        "a": "Any memorable phrase — the key just needs to exist.",
        "b": "A long, random string of at least 32 characters generated by a tool, never reused elsewhere.",
        "c": "The server's IP address for uniqueness.",
        "d": "The admin's username for easy recovery.",
        "correct": "b",
        "explanation": "SECRET_KEY signs session cookies. A short, guessable, or default key can be brute-forced, letting attackers forge sessions. A 32+ character random string (like `python -c 'import secrets; print(secrets.token_hex(32))'`) is computationally infeasible to guess. Never use the same key on multiple projects — if one leaks, all are compromised.",
        "topic": "security",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "`git add .` vs `git add specific-file.py` — when should you use each?",
        "a": "Always use `git add .` — it is faster.",
        "b": "Use `git add .` only in new projects with no sensitive files. Use specific file adds when you want control over exactly what goes into a commit.",
        "c": "Use `git add specific-file.py` always — `git add .` is dangerous.",
        "d": "They are identical if you have a proper .gitignore.",
        "correct": "b",
        "explanation": "`git add .` stages everything not in .gitignore. This is convenient but risky — you might accidentally stage a log file, a temp file, or a secret that slipped through .gitignore. Staging specific files gives you explicit control. For this project, being deliberate about what you add is the safer habit.",
        "topic": "git",
        "difficulty": 2
    },
    {
        "phase": 0,
        "text": "What does `not (a and b)` equal in terms of `not a` and `not b`? (De Morgan's Law)",
        "a": "`not a and not b`",
        "b": "`not a or not b`",
        "c": "`not a and b`",
        "d": "They are not equivalent — De Morgan's Law does not apply in Python.",
        "correct": "b",
        "explanation": "De Morgan's Law: `not (a and b)` equals `(not a) or (not b)`. And `not (a or b)` equals `(not a) and (not b)`. This matters when writing conditions: `if not (user.is_admin and user.is_active)` is the same as `if not user.is_admin or not user.is_active`. Understanding this prevents logic bugs in access control.",
        "topic": "python",
        "difficulty": 3
    },
]
